[package]
name = "database"
edition = "2021"

[workspace]
members = ["derive"]

[dependencies]
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros", "net", "io-util", "time"] }
database_derive = { path = "derive" }
